import type { EditorState, Obstacle, ObstacleShape, TextShape } from './types'

const CLIP_PATHS: Record<ObstacleShape, string | null> = {
  rect:            null,
  circle:          null, // generated dynamically in obstacleClipPath
  'triangle-up':   'polygon(50% 0%, 0% 100%, 100% 100%)',
  'triangle-down': 'polygon(0% 0%, 100% 0%, 50% 100%)',
  diamond:         'polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%)',
}

function serializeObstacle(o: Obstacle): string {
  const parts: string[] = [
    `id: '${o.id}'`,
    `x: ${o.x}`, `y: ${o.y}`,
    `width: ${o.width}`, `height: ${o.height}`,
  ]
  if (o.shape && o.shape !== 'rect') parts.push(`shape: '${o.shape}' as ObstacleShape`)
  if (o.padding)                     parts.push(`padding: ${o.padding}`)
  if (o.imageUrl)                    parts.push(`imageUrl: '${o.imageUrl.replace(/'/g, '%27')}'`)
  return `    { ${parts.join(', ')} }`
}

function serializeText(text: string): string {
  // Escape backticks and bare $ so the text can sit inside a template literal
  return text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${')
}

export function generateReactCode(state: EditorState): string {
  const W = state.containerWidth
  const H = state.containerHeight

  const layersStr = state.textBlocks.map((block) => {
    const obstaclesStr = block.obstacles.length
      ? block.obstacles.map(serializeObstacle).join(',\n')
      : ''
    const textShapeStr = block.textShape && block.textShape !== 'rect'
      ? `\n    textShape: '${block.textShape}' as TextShape,`
      : ''
    return `  {
    font: '${block.font}', fontSize: ${block.fontSize}, lineHeight: ${block.lineHeight}, color: '${block.color}',${textShapeStr}
    obstacles: [\n${obstaclesStr}\n    ] as Obstacle[],
    text: \`${serializeText(block.text)}\`,
  }`
  }).join(',\n')

  return `// Generated by Pretext Playground
// Requires: npm install @chenglou/pretext

'use client'

import { prepareWithSegments, layoutNextLine, type LayoutCursor } from '@chenglou/pretext'

// ─── Types ──────────────────────────────────────────────────────────────────

type ObstacleShape = 'rect' | 'circle' | 'triangle-up' | 'triangle-down' | 'diamond'
type TextShape = 'rect' | 'pyramid' | 'inverted-pyramid' | 'diamond' | 'wave'
type Obstacle = { id: string; x: number; y: number; width: number; height: number; shape?: ObstacleShape; padding?: number; imageUrl?: string }
type Segment = { x: number; width: number }
type RenderedLine = { text: string; x: number; y: number; width: number }

// ─── Engine ─────────────────────────────────────────────────────────────────

function getObstacleRange(o: Obstacle, midY: number): [number, number] | null {
  const pad = o.padding ?? 0
  const x = o.x - pad, oy = o.y - pad
  const width = o.width + pad * 2, height = o.height + pad * 2
  if (midY < oy || midY > oy + height) return null
  const t = (midY - oy) / height, cx = x + width / 2
  switch (o.shape ?? 'rect') {
    case 'rect': return [x, x + width]
    case 'circle': {
      const r = Math.min(width, height) / 2, cy = oy + height / 2, dy = midY - cy
      if (Math.abs(dy) >= r) return null
      const hw = Math.sqrt(r * r - dy * dy)
      return [cx - hw, cx + hw]
    }
    case 'triangle-up': return [cx - t * width / 2, cx + t * width / 2]
    case 'triangle-down': { const inv = 1 - t; return [cx - inv * width / 2, cx + inv * width / 2] }
    case 'diamond': {
      const hw = (1 - Math.abs(t - 0.5) * 2) * width / 2
      if (hw <= 1) return null
      return [cx - hw, cx + hw]
    }
    default: return [x, x + width]
  }
}

function getAllSegments(y: number, lh: number, bw: number, obs: Obstacle[]): Segment[] {
  const midY = y + lh / 2
  const blocked: [number, number][] = obs.flatMap(o => { const r = getObstacleRange(o, midY); return r ? [r] : [] })
  if (!blocked.length) return [{ x: 0, width: bw }]
  const pts = new Set<number>([0, bw])
  for (const [l, r] of blocked) { pts.add(Math.max(0, l)); pts.add(Math.min(bw, r)) }
  const sorted = [...pts].sort((a, b) => a - b)
  return sorted.slice(0, -1).flatMap((x, i) => {
    const w = sorted[i + 1] - x
    return !blocked.some(([l, r]) => l < sorted[i + 1] && r > x) && w >= 10 ? [{ x, width: w }] : []
  })
}

function getTextShapeSegment(y: number, lh: number, bh: number, bw: number, shape: TextShape): Segment {
  const t = (y + lh / 2) / Math.max(bh, 1), cx = bw / 2
  let w: number, x: number
  switch (shape) {
    case 'pyramid':          w = Math.max(30, bw * (1 - t * 0.84));          x = cx - w / 2; break
    case 'inverted-pyramid': w = Math.max(30, bw * (0.16 + t * 0.84));       x = cx - w / 2; break
    case 'diamond': {        const dt = Math.abs(t - 0.5) * 2; w = Math.max(30, bw * (1 - dt * 0.78)); x = cx - w / 2; break }
    case 'wave':             w = Math.max(40, bw * (0.62 + Math.sin(t * Math.PI * 4) * 0.2)); x = cx - w / 2 + Math.sin(t * Math.PI * 2.5) * bw * 0.1; break
    default: return { x: 0, width: bw }
  }
  const ox = Math.max(0, x)
  return { x: ox, width: Math.max(10, Math.min(w, bw - ox)) }
}

function computeLayout(
  text: string, font: string, lh: number, bw: number, bh: number,
  obs: Obstacle[], textShape?: TextShape,
): RenderedLine[] {
  if (!text.trim()) return []
  const prepared = prepareWithSegments(text, font)
  const lines: RenderedLine[] = []
  let cursor: LayoutCursor = { segmentIndex: 0, graphemeIndex: 0 }
  let y = 0, done = false
  while (y < bh && !done) {
    let segs = getAllSegments(y, lh, bw, obs)
    if (textShape && textShape !== 'rect') {
      const clip = getTextShapeSegment(y, lh, bh, bw, textShape)
      const end = clip.x + clip.width
      segs = segs.flatMap(s => { const sx = Math.max(s.x, clip.x), ex = Math.min(s.x + s.width, end); return ex - sx >= 10 ? [{ x: sx, width: ex - sx }] : [] })
    }
    if (!segs.length) { y += lh; continue }
    for (const seg of segs) {
      const line = layoutNextLine(prepared, cursor, seg.width)
      if (!line) { done = true; break }
      lines.push({ text: line.text, x: seg.x, y, width: seg.width })
      cursor = line.end
    }
    y += lh
  }
  return lines
}

function obstacleClipPath(o: Obstacle): string | undefined {
  switch (o.shape) {
    case 'circle':        return \`circle(\${Math.min(o.width, o.height) / 2}px at 50% 50%)\`
    case 'triangle-up':   return 'polygon(50% 0%, 0% 100%, 100% 100%)'
    case 'triangle-down': return 'polygon(0% 0%, 100% 0%, 50% 100%)'
    case 'diamond':       return 'polygon(50% 0%, 100% 50%, 50% 100%, 0% 50%)'
  }
}

// ─── Data ───────────────────────────────────────────────────────────────────

const P = 20 // canvas padding

const layers = [
${layersStr}
]

// ─── Component ──────────────────────────────────────────────────────────────

export function ObstacleLayout() {
  return (
    <div style={{ position: 'relative', width: ${W}, height: ${H}, overflow: 'hidden' }}>
      {layers.flatMap((layer, li) => {
        const lines = computeLayout(
          layer.text,
          \`\${layer.fontSize}px \${layer.font}\`,
          layer.lineHeight,
          ${W} - P * 2,
          ${H} - P * 2,
          layer.obstacles,
          layer.textShape,
        )
        return [
          ...layer.obstacles.map((o) => (
            <div
              key={\`\${li}-\${o.id}\`}
              style={{
                position: 'absolute', left: o.x + P, top: o.y + P,
                width: o.width, height: o.height,
                clipPath: obstacleClipPath(o),
                ...(o.imageUrl ? { backgroundImage: \`url(\${o.imageUrl})\`, backgroundSize: 'cover', backgroundPosition: 'center' } : {}),
              }}
            />
          )),
          ...lines.map((line, i) => (
            <span
              key={\`\${li}-l\${i}\`}
              style={{
                position: 'absolute', left: line.x + P, top: line.y + P,
                whiteSpace: 'nowrap', fontFamily: layer.font,
                fontSize: layer.fontSize, lineHeight: \`\${layer.lineHeight}px\`,
                color: layer.color,
              }}
            >
              {line.text}
            </span>
          )),
        ]
      })}
    </div>
  )
}
`
}
